In [1]:
from numpy import *

In [2]:
arr = array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [4]:
arr = array([1,2,3,4,5])
print(arr.dtype)

float64


In [5]:
arr = array([1,2,3.0,4,5])
print(arr.dtype)
print(arr)

float64
[1. 2. 3. 4. 5.]


In [8]:
arr = linspace(0,15,20) #(start,stop,no of parts)
print(arr)

[ 0.          0.78947368  1.57894737  2.36842105  3.15789474  3.94736842
  4.73684211  5.52631579  6.31578947  7.10526316  7.89473684  8.68421053
  9.47368421 10.26315789 11.05263158 11.84210526 12.63157895 13.42105263
 14.21052632 15.        ]


In [9]:
arr = linspace(0,15) #(start,stop,by default-50)
print(arr)

[ 0.          0.30612245  0.6122449   0.91836735  1.2244898   1.53061224
  1.83673469  2.14285714  2.44897959  2.75510204  3.06122449  3.36734694
  3.67346939  3.97959184  4.28571429  4.59183673  4.89795918  5.20408163
  5.51020408  5.81632653  6.12244898  6.42857143  6.73469388  7.04081633
  7.34693878  7.65306122  7.95918367  8.26530612  8.57142857  8.87755102
  9.18367347  9.48979592  9.79591837 10.10204082 10.40816327 10.71428571
 11.02040816 11.32653061 11.63265306 11.93877551 12.24489796 12.55102041
 12.85714286 13.16326531 13.46938776 13.7755102  14.08163265 14.3877551
 14.69387755 15.        ]


In [10]:
arr =arange(1,15,2) #(start,stop,skipping steps)
print(arr)

[ 1  3  5  7  9 11 13]


In [11]:
arr = logspace(1,40,5) #10raiseto1,10raiseto40,5 parts)
print(arr)

[1.00000000e+01 5.62341325e+10 3.16227766e+20 1.77827941e+30
 1.00000000e+40]


In [14]:
arr = logspace(1,40,5) #10raiseto1,10raiseto40,5 parts)
print('%.2f' %arr[3])

1778279410038922838185969975296.00


In [15]:
arr = zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [17]:
arr = ones(5,int)
print(arr)

[1 1 1 1 1]


In [18]:
arr = array([1,2,3,4,5])
arr = arr + 5
print(arr)

[ 6  7  8  9 10]


In [19]:
arr1 = array([1,2,3,4,5])
arr2 = array([6,1,9,3,2])
arr3 = arr1 +arr2
print(arr3)

[ 7  3 12  7  7]


In [20]:
arr1 = array([1,2,3,4,5])
print(sin(arr1))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [21]:
arr1 = array([1,2,3,4,5])
print(cos(arr1))

[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


In [22]:
arr1 = array([1,2,3,4,5])
print(log(arr1))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [23]:
arr1 = array([1,2,3,4,5])
print(sqrt(arr1))

[1.         1.41421356 1.73205081 2.         2.23606798]


In [24]:
arr1 = array([1,2,3,4,5])
print(sum(arr1))

15


In [25]:
arr1 = array([1,2,3,4,5])
print(max(arr1))

5


In [26]:
arr1 = array([1,2,3,4,5])
arr2 = array([6,1,9,3,2])
print(concatenate([arr1,arr2]))

[1 2 3 4 5 6 1 9 3 2]


# Copying an Array

In [29]:
arr1 = array([2,6,8,1,3])
arr2 = arr1
print(arr1)
print(arr2)
print(id(arr1))
print(id(arr2))

[2 6 8 1 3]
[2 6 8 1 3]
3012784512336
3012784512336


In [31]:
arr1 = array([2,6,8,1,3])
arr2 = arr1.view() #view help us to create new array at differnt location
print(arr1)
print(arr2)
print()
print(id(arr1))
print(id(arr2))

[2 6 8 1 3]
[2 6 8 1 3]

3012784625584
3012784625824


In [33]:
#shallow copy
arr1 = array([2,6,8,1,3])
arr2 = arr1.view()
arr1[1] = 7
print(arr1)
print(arr2)
print(id(arr1))
print(id(arr2))

[2 7 8 1 3]
[2 7 8 1 3]
3012784652416
3012784652576


In [34]:
#Deep copy : two different arrays which are not linked together
arr1 = array([2,6,8,1,3])
arr2 = arr1.copy() #copy
arr1[1] = 7
print(arr1)
print(arr2)
print(id(arr1))
print(id(arr2))

[2 7 8 1 3]
[2 6 8 1 3]
3012784653296
3012784653456


In [42]:
#Adding 2 arrays using for loop
arr1 = array([1,2,3,4,5])
arr2 = array([2,3,4,5,6])
arr3 = ([])
k = 0
for i in arr1:
    j = i + arr2[k]
    arr3.append(j)
    k +=1
print(arr3)

[3, 5, 7, 9, 11]


In [38]:
arr1 = array([1,2,3,4,5])
arr2 = array([2,3,4,5,6])
for i in range(len(arr1)):
    arr3 = arr1[i] + arr2[i]
    print(arr3,end=" ")

3 5 7 9 11 

In [48]:
arr = array([4,8,52,34,21,10])
max = 0
for i in range(len(arr)):
    if arr[i] >= max :
        max = arr[i]
print(max)

52
