In [1]:
from numpy import *

In [3]:
arr1 = array([[1,2,3,4],[4,5,6,7]])
m = matrix(arr1)
print(m)

[[1 2 3 4]
 [4 5 6 7]]


In [5]:
#arr1 = array([[1,2,3,4],[4,5,6,7]])
m = matrix('1 2 3 4 ; 4 5 6 7')
print(m)

[[1 2 3 4]
 [4 5 6 7]]


In [10]:
m = matrix('1 2 3 ; 4 5 6 ; 7 8 9')
print(m)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
m = matrix('1 2 3 ; 4 5 6 ; 7 8 9')
print(diagonal(m))

[1 5 9]


In [12]:
m = matrix('1 2 3 ; 4 5 6 ; 7 8 9')
print(m.max())

9


In [14]:
m1 = matrix('1 2 3 ; 4 5 6 ; 7 8 9')
m2 = matrix('1 2 3 ; 4 2 6 ; 3 8 9')
m3 = m1 * m2
print(m3)

[[ 18  30  42]
 [ 42  66  96]
 [ 66 102 150]]
