In [1]:
from numpy import *

In [2]:
arr1 = array([[1,2,3],[4,5,6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


In [4]:
arr1 = array([[1,2,3],[4,5,6]])
print(arr1.ndim) #ndim gives no of dimension

2


In [6]:
arr1 = array([[1,2,3],[4,5,6]])
print(arr1.shape) #shape gives no of rows and column

(2, 3)


In [7]:
arr1 = array([[1,2,3],[4,5,6]])
print(arr1.size)

6


# Covert N-D array to 1-D array

In [8]:
arr1 = array([[1,2,3],[4,5,6]])
arr2 = arr1.flatten()
print(arr2)

[1 2 3 4 5 6]


# Covert 1-D array to n-D array

In [10]:
arr1 = array([[1,2,3,6,2,9],[4,5,6,7,8,9]])
arr2 = arr1.flatten()
arr3 = arr2.reshape(2,2,3)
print(arr3)

[[[1 2 3]
  [6 2 9]]

 [[4 5 6]
  [7 8 9]]]
